using Content.Client._Moffstation.CartridgeLoader.Cartridges;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class LogProbeUiFragment : BoxContainer
{
    public Action? OnPrintPressed;
    public Action<Guid>? OnChitterPrintArchive;

    public LogProbeUiFragment()
    {
        RobustXamlLoader.Load(this);

        PrintButton.OnPressed += _ => OnPrintPressed?.Invoke();
    }

    public void UpdateState(LogProbeUiState state)
    {
        EntityName.Text = state.EntityName;
        PrintButton.Disabled = string.IsNullOrEmpty(state.EntityName);

        ProbedDeviceContainer.RemoveAllChildren();

        if (state.ChitterData != null)
        {
            SetupChitterView(state.ChitterData);
            return;
        }

        if (state.PulledLogs.Count > 0)
            DisplayAccessLogs(state.PulledLogs);
    }

    private void SetupChitterView(ChitterServerScanData data)
    {
        TitleLabel.Text = Loc.GetString("chitter-logprobe-header");
        ContentLabel.Text = Loc.GetString("chitter-logprobe-label-chat");
        CardNumberLabel.Visible = false;
        PrintButton.Visible = false;

        if (data.ArchivedChats.Count == 0)
        {
            ProbedDeviceContainer.AddChild(new Label
            {
                Text = Loc.GetString("chitter-logprobe-no-archives"),
            });
            return;
        }

        foreach (var chat in data.ArchivedChats)
        {
            var entry = new ChitterLogEntry
            {
                Participants = chat.Participants,
                MessageCount = chat.MessageCount,
                LastMessage = chat.LastMessagePreview,
            };

            var capturedId = chat.ChatId;
            entry.OnPrintPressed += () => OnChitterPrintArchive?.Invoke(capturedId);

            ProbedDeviceContainer.AddChild(entry);
        }
    }

    private void DisplayAccessLogs(List<PulledAccessLog> logs)
    {
        TitleLabel.Text = Loc.GetString("log-probe-header-access");
        ContentLabel.Text = Loc.GetString("log-probe-label-accessor");
        CardNumberLabel.Visible = false;
        PrintButton.Visible = true;

        var count = 1;
        for (var i = logs.Count - 1; i >= 0; i--)
        {
            AddAccessLog(logs[i], count);
            count++;
        }
    }

    private void AddAccessLog(PulledAccessLog log, int numberLabelText)
    {
        var timeLabelText = TimeSpan.FromSeconds(Math.Truncate(log.Time.TotalSeconds)).ToString();
        var accessorLabelText = log.Accessor;
        var entry = new LogProbeUiEntry(numberLabelText, timeLabelText, accessorLabelText);

        ProbedDeviceContainer.AddChild(entry);
    }
}
