using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class StampWidget : PanelContainer
{
    public float Orientation
    {
        get => StampedByLabel.Orientation;
        set
        {
            StampedByLabel.Orientation = value;
            StampedByIcon.Orientation = value;
        }
    }

    public StampDisplayInfo StampInfo {
        set {
            // Signatures are handwriting, not a themed job stamp, so they keep the text rendering.
            var isSignature = value.Type is StampType.Signature;

            StampedByLabel.Visible = isSignature;
            StampedByIcon.Visible = !isSignature;

            if (isSignature)
            {
                // Umbra: If it's a signature, don't bother doing a string lookup.
                StampedByLabel.Text = value.StampedName;
                StampedByLabel.FontColorOverride = value.StampedColor;
            }
            else
            {
                // The icon art already includes its own themed border, unlike the text label.
                StampedByIcon.RsiState = value.StampState;
            }
        }
    }

    public StampWidget()
    {
        RobustXamlLoader.Load(this);
    }
}
