using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Input;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChitterChatListEntry : BoxContainer
{
    public string DisplayName
    {
        set => NameLabel.Text = value;
    }

    public string LastMessage
    {
        set => MessageLabel.Text = value;
    }

    public bool HasUnread
    {
        set => NameLabel.FontColorOverride = value ? Color.Green : null;
    }

    public int UnreadCount
    {
        set
        {
            UnreadCountLabel.Visible = value > 0;
            UnreadCountLabel.Text = $"({value})";
        }
    }

    public event Action? OnPressed;

    public ChitterChatListEntry()
    {
        RobustXamlLoader.Load(this);

        MouseFilter = MouseFilterMode.Stop;
        OnKeyBindDown += args =>
        {
            if (args.Function == EngineKeyFunctions.UIClick || args.Function == EngineKeyFunctions.Use)
                OnPressed?.Invoke();
        };
    }
}
