using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChitterChatListEntry : BoxContainer
{
    private Button? _button;

    public string DisplayName
    {
        set => NameLabel.Text = value;
    }

    public string LastMessage
    {
        set => MessageLabel.Text = value;
    }

    public bool HasUnread
    {
        set => NameLabel.FontColorOverride = value ? Color.Green : null;
    }

    public int UnreadCount
    {
        set
        {
            UnreadCountLabel.Visible = value > 0;
            UnreadCountLabel.Text = $"({value})";
        }
    }

    public event Action? OnPressed;

    public ChitterChatListEntry()
    {
        RobustXamlLoader.Load(this);

        _button = new Button
        {
            HorizontalExpand = true,
            VerticalExpand = true,
            Visible = false,
        };
        AddChild(_button);

        OnMouseEntered += _ => _button.Visible = true;
        OnMouseExited += _ => _button.Visible = false;

        _button.OnPressed += _ => OnPressed?.Invoke();
    }
}
