using System.Linq;
using Content.Shared._Moffstation.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChitterLookupView : BoxContainer
{
    private List<AccountEntry> _contacts = null!;
    private HashSet<uint> _selectedIds = new();

    public event Action<List<uint>>? OnChatCreated;
    public event Action? OnClose;

    public ChitterLookupView()
    {
        RobustXamlLoader.Load(this);
    }

    public ChitterLookupView(List<AccountEntry> contacts) : this()
    {
        _contacts = contacts;

        CloseLookupButton.OnPressed += _ => OnClose?.Invoke();
        CreateChatButton.OnPressed += _ =>
        {
            if (_selectedIds.Count > 0)
                OnChatCreated?.Invoke(_selectedIds.ToList());
        };

        SearchInput.OnTextChanged += _ =>
        {
            var search = SearchInput.Text.Trim().ToLower();
            UpdateResults(search);
        };

        UpdateResults("");
    }

    private void UpdateResults(string search)
    {
        SearchResults.RemoveAllChildren();
        _selectedIds.Clear();
        CreateChatButton.Disabled = true;

        foreach (var contact in _contacts)
        {
            if (!string.IsNullOrEmpty(search) && !contact.Name.ToLower().Contains(search))
                continue;

            var btn = new Button
            {
                Text = $"{contact.Name} (#{contact.AccountId:D4})",
                HorizontalExpand = true,
                ToggleMode = true,
            };
            var capturedId = contact.AccountId;
            btn.OnToggled += (args) =>
            {
                if (args.Pressed)
                    _selectedIds.Add(capturedId);
                else
                    _selectedIds.Remove(capturedId);

                CreateChatButton.Disabled = _selectedIds.Count == 0;
            };
            SearchResults.AddChild(btn);
        }
    }
}
