using System.Linq;
using Content.Shared._Moffstation.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Numerics;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChitterProfileView : BoxContainer
{
    public event Action<string>? OnProfilePictureSelected;
    public event Action? OnClose;

    public ChitterProfileView()
    {
        RobustXamlLoader.Load(this);
    }

    public ChitterProfileView(List<string> avatarIds, string currentAvatarId) : this()
    {
        CloseProfileButton.OnPressed += _ => OnClose?.Invoke();

        foreach (var avatarId in avatarIds)
        {
            var btn = new Button
            {
                Text = avatarId,
                MinSize = new Vector2(48, 48),
                Pressed = avatarId == currentAvatarId,
            };
            var capturedId = avatarId;
            btn.OnPressed += _ =>
            {
                OnProfilePictureSelected?.Invoke(capturedId);
                OnClose?.Invoke();
            };
            AvatarGrid.AddChild(btn);
        }
    }
}
