using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChitterLogEntry : BoxContainer
{
    public string Participants
    {
        set => ParticipantsLabel.Text = value;
    }

    public int MessageCount
    {
        set => CountLabel.Text = Loc.GetString("chitter-logprobe-message-count", ("count", value));
    }

    public string LastMessage
    {
        set => MessageLabel.Text = value;
    }

    public event Action? OnPrintPressed;

    public ChitterLogEntry()
    {
        RobustXamlLoader.Load(this);

        PrintButton.OnPressed += _ => OnPrintPressed?.Invoke();
    }
}
