using Content.Shared._Moffstation.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChitterMessageBubble : BoxContainer
{
    private static readonly Color OwnBubbleColor = new(0.1f, 0.3f, 0.1f);
    private static readonly Color OtherBubbleColor = new(0.15f, 0.15f, 0.15f);

    public string SenderName
    {
        set => SenderLabel.Text = value;
    }

    public string Message
    {
        set => MessageLabel.Text = value;
    }

    public TimeSpan Timestamp
    {
        set => TimestampLabel.Text = TimeSpan.FromSeconds(Math.Truncate(value.TotalSeconds)).ToString();
    }

    public bool IsOwn
    {
        set
        {
            BubbleBackground.ModulateSelfOverride = value ? OwnBubbleColor : OtherBubbleColor;
            SenderLabel.Visible = !value;
        }
    }

    public bool DeliveryFailed
    {
        set => FailedLabel.Visible = value;
    }

    public ChitterMessageBubble()
    {
        RobustXamlLoader.Load(this);
    }
}
