using System.Linq;
using Content.Shared._Moffstation.CartridgeLoader.Cartridges;
using Content.Shared._Moffstation.Chitter;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Moffstation.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChitterUiFragment : BoxContainer
{
    private ChitterUiState _currentState = new();
    private Guid? _selectedChatId;
    private readonly IPrototypeManager _prototypeManager;

    public Action<ChitterUiMessageType, Guid?, uint?, List<uint>?, string?, string?, string?>? OnUiMessage;

    public ChitterUiFragment()
    {
        RobustXamlLoader.Load(this);
        _prototypeManager = IoCManager.Resolve<IPrototypeManager>();

        NewChatButton.OnPressed += _ => ShowNewChat();
        ProfileButton.OnPressed += _ => ShowProfile();
        SendButton.OnPressed += _ => SendCurrentMessage();
        MessageInput.OnTextEntered += _ => SendCurrentMessage();
        ManageChatButton.OnPressed += _ => ShowManageChat();
    }

    public void UpdateState(ChitterUiState state)
    {
        _currentState = state;

        if (!state.HasIdCard)
        {
            WarningBanner.Visible = true;
            WarningLabel.Text = Loc.GetString("chitter-no-account");
            ChatView.Visible = false;
            ChatList.Visible = false;
            NewChatButton.Disabled = true;
            ProfileButton.Disabled = true;
            return;
        }

        if (!state.ServerOnline && state.HasIdCard)
        {
            WarningBanner.Visible = true;
            WarningLabel.Text = Loc.GetString("chitter-server-offline");
        }
        else
        {
            WarningBanner.Visible = false;
        }

        NewChatButton.Disabled = false;
        ProfileButton.Disabled = false;

        PopulateChatList(state);

        if (_selectedChatId != null && state.CurrentChat?.ChatId == _selectedChatId)
        {
            ShowChatView(state.CurrentChat);
        }
        else if (_selectedChatId != null && state.Chats.Any(c => c.ChatId == _selectedChatId))
        {
            OnUiMessage?.Invoke(ChitterUiMessageType.SelectChat, _selectedChatId, null, null, null, null, null);
        }
        else
        {
            NoChatPlaceholder.Visible = true;
            ChatView.Visible = false;
        }
    }

    private void ShowOverlay(Control view)
    {
        MainContent.Visible = false;
        OverlayContainer.RemoveAllChildren();
        OverlayContainer.AddChild(view);
        OverlayContainer.Visible = true;
    }

    private void HideOverlay()
    {
        OverlayContainer.Visible = false;
        OverlayContainer.RemoveAllChildren();
        MainContent.Visible = true;
    }

    private void PopulateChatList(ChitterUiState state)
    {
        ChatList.RemoveAllChildren();

        foreach (var chat in state.Chats)
        {
            var entry = new ChitterChatListEntry
            {
                DisplayName = chat.DisplayName,
                LastMessage = chat.LastMessage,
                HasUnread = chat.HasUnread,
                UnreadCount = chat.UnreadCount,
            };

            var capturedId = chat.ChatId;
            entry.OnPressed += () =>
            {
                _selectedChatId = capturedId;
                OnUiMessage?.Invoke(ChitterUiMessageType.SelectChat, capturedId, null, null, null, null, null);
            };

            ChatList.AddChild(entry);
        }
    }

    private void ShowChatView(ChatDetail? detail)
    {
        HideOverlay();

        if (detail == null)
        {
            NoChatPlaceholder.Visible = true;
            ChatView.Visible = false;
            return;
        }

        NoChatPlaceholder.Visible = false;
        ChatView.Visible = true;

        ChatTitle.Text = string.Join(", ", detail.Participants.Select(p => p.Name));

        MessageContainer.RemoveAllChildren();

        foreach (var msg in detail.Messages)
        {
            var bubble = new ChitterMessageBubble
            {
                SenderName = msg.SenderName,
                Message = msg.Content,
                Timestamp = msg.Timestamp,
                IsOwn = msg.IsOwn,
                DeliveryFailed = msg.DeliveryFailed,
            };
            MessageContainer.AddChild(bubble);
        }
    }

    private void ShowManageChat()
    {
        if (_currentState.CurrentChat == null)
            return;

        var view = new ChitterManageChatView(_currentState.CurrentChat, _currentState.Contacts);
        view.OnBack += HideOverlay;
        view.OnAddParticipant += (id) => OnUiMessage?.Invoke(ChitterUiMessageType.AddParticipant, _currentState.CurrentChat.ChatId, id, null, null, null, null);
        view.OnRemoveParticipant += (id) => OnUiMessage?.Invoke(ChitterUiMessageType.RemoveParticipant, _currentState.CurrentChat.ChatId, id, null, null, null, null);
        view.OnLeaveChat += () =>
        {
            OnUiMessage?.Invoke(ChitterUiMessageType.LeaveChat, _currentState.CurrentChat.ChatId, null, null, null, null, null);
            HideOverlay();
            _selectedChatId = null;
        };
        view.OnArchive += () =>
        {
            OnUiMessage?.Invoke(ChitterUiMessageType.ArchiveChat, _currentState.CurrentChat.ChatId, null, null, null, null, null);
            HideOverlay();
            _selectedChatId = null;
        };
        ShowOverlay(view);
    }

    private void ShowNewChat()
    {
        if (_currentState.Contacts.Count == 0)
            return;

        var view = new ChitterLookupView(_currentState.Contacts);
        view.OnChatCreated += (targetIds) =>
        {
            OnUiMessage?.Invoke(ChitterUiMessageType.NewChat, null, null, targetIds, null, null, null);
            HideOverlay();
        };
        view.OnClose += HideOverlay;
        ShowOverlay(view);
    }

    private void ShowProfile()
    {
        var avatarIds = _prototypeManager.EnumeratePrototypes<ChitterAvatarPrototype>()
            .Select(p => p.ID)
            .ToList();

        var view = new ChitterProfileView(avatarIds, _currentState.OwnProfilePicture);
        view.OnProfilePictureSelected += (id) =>
        {
            OnUiMessage?.Invoke(ChitterUiMessageType.SetProfilePicture, null, null, null, null, null, id);
            HideOverlay();
        };
        view.OnClose += HideOverlay;
        ShowOverlay(view);
    }

    private void SendCurrentMessage()
    {
        var text = MessageInput.Text.Trim();
        if (string.IsNullOrEmpty(text) || _selectedChatId == null)
            return;

        OnUiMessage?.Invoke(ChitterUiMessageType.SendMessage, _selectedChatId, null, null, text, null, null);
        MessageInput.Text = "";
    }
}
